<a href="https://colab.research.google.com/github/Harini-0204/Projects-Using-Python/blob/main/Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

In [ ]:
import numpy as np

In [ ]:
my_list_1=[2,6,8,12,0]
my_list_2=[3,4,-2,5,6]
my_list_3=[0,11,4,9,6]

arr_new=np.array([my_list_1,my_list_2,my_list_3])
print(arr_new)


[[ 2  6  8 12  0]
 [ 3  4 -2  5  6]
 [ 0 11  4  9  6]]


In [ ]:
my_list_1=[2,6,8,12,0]
my_list_2=[3,4,-2,5,6]
my_list_3=[0,11,4,9,6]
my_list_4=[2,6,8,12,0]
my_list_5=[3,4,-2,5,6]
my_list_6=[0,11,4,9,6]
arr=np.array([my_list_1,my_list_2,my_list_3,my_list_4,my_list_5,my_list_6])
print(arr)

[[ 2  6  8 12  0]
 [ 3  4 -2  5  6]
 [ 0 11  4  9  6]
 [ 2  6  8 12  0]
 [ 3  4 -2  5  6]
 [ 0 11  4  9  6]]


In [ ]:
a=np.arange(0,20,3)
print(a)

[ 0  3  6  9 12 15 18]


In [ ]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.linspace(1,10,70)

array([ 1.        ,  1.13043478,  1.26086957,  1.39130435,  1.52173913,
        1.65217391,  1.7826087 ,  1.91304348,  2.04347826,  2.17391304,
        2.30434783,  2.43478261,  2.56521739,  2.69565217,  2.82608696,
        2.95652174,  3.08695652,  3.2173913 ,  3.34782609,  3.47826087,
        3.60869565,  3.73913043,  3.86956522,  4.        ,  4.13043478,
        4.26086957,  4.39130435,  4.52173913,  4.65217391,  4.7826087 ,
        4.91304348,  5.04347826,  5.17391304,  5.30434783,  5.43478261,
        5.56521739,  5.69565217,  5.82608696,  5.95652174,  6.08695652,
        6.2173913 ,  6.34782609,  6.47826087,  6.60869565,  6.73913043,
        6.86956522,  7.        ,  7.13043478,  7.26086957,  7.39130435,
        7.52173913,  7.65217391,  7.7826087 ,  7.91304348,  8.04347826,
        8.17391304,  8.30434783,  8.43478261,  8.56521739,  8.69565217,
        8.82608696,  8.95652174,  9.08695652,  9.2173913 ,  9.34782609,
        9.47826087,  9.60869565,  9.73913043,  9.86956522, 10.  

In [ ]:
GENERATING RANDOM NUMBERS

In [ ]:
np.random.rand(3,4)

array([[0.04233724, 0.60931335, 0.27570338, 0.86665168],
       [0.2517952 , 0.41883456, 0.67988201, 0.23523721],
       [0.02792939, 0.29198012, 0.6312395 , 0.90882619]])

In [ ]:
np.random.randint(1,20,100)  # here 100 denotes the no of elements we want in the given range

array([11, 19,  1, 14, 11, 19,  2,  1,  7,  4, 14, 11, 10,  3, 13,  4,  3,
       17, 13, 13, 10,  6, 19,  6, 13,  3, 12,  7,  3,  6, 11,  9,  9,  3,
        5, 13,  8,  9,  4, 12,  7, 19,  1, 18,  9, 19,  5,  9, 14,  3, 15,
       15,  4,  5,  5,  1, 12,  4,  2, 14, 19, 19,  8,  1, 10, 13,  2,  8,
        7,  4, 14,  8, 13, 13,  4, 10, 17, 18, 16, 15, 13, 10, 15, 18,  8,
        7,  7, 11, 11, 11,  8, 19,  2,  7, 17, 18,  9, 14,  4,  1])

In [ ]:
np.random.randint(1,20,size=(2,3)) # creating 2D array

array([[ 1,  7, 15],
       [ 5, 17,  8]])

PANDAS

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("/content/tips.csv")

In [ ]:
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
data.head(10)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [ ]:
data.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
my_data=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['a','b','c','d','e'],columns=[1,2,3,4]) #why it is not accepting rows as name in the place of index and also another name in the place of columns
print(my_data)

    1   2   3   4
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15
e  16  17  18  19


In [ ]:
my_data.to_csv('my_data.csv')

In [ ]:
my_data.to_excel('my_data.xlsx')

Indexing and slicing


In [ ]:
import numpy as np
import pandas as pd

my_data=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['a','b','c','d','e'],columns=['col1','col2','col3','col4']) #why it is not accepting rows as name in the place of index and also another name in the place of columns
print(my_data)

   col1  col2  col3  col4
a     0     1     2     3
b     4     5     6     7
c     8     9    10    11
d    12    13    14    15
e    16    17    18    19


In [ ]:
my_data.iloc[2:4, 2:]

col3  col4
c    10    11
d    14    15

In [ ]:
my_data.iloc[:,:]

col1  col2  col3  col4
a     0     1     2     3
b     4     5     6     7
c     8     9    10    11
d    12    13    14    15
e    16    17    18    19